/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_standopen_test_Data */

#ifndef _Included_com_standopen_test_Data
#define _Included_com_standopen_test_Data
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_standopen_test_Data
 * Method:    callhellofromjava
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_standopen_test_Data_callhellofromjava
  (JNIEnv *, jobject);

/*
 * Class:     com_standopen_test_Data
 * Method:    calladd
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_standopen_test_Data_calladd
  (JNIEnv *, jobject);

/*
 * Class:     com_standopen_test_Data
 * Method:    callprintstring
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_standopen_test_Data_callprintstring
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
