/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_standopen_socket_Main */

#ifndef _Included_com_standopen_socket_Main
#define _Included_com_standopen_socket_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_standopen_socket_Main
 * Method:    SendMsg
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_standopen_socket_Main_SendMsg
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
