/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_standopen_hello_MainActivity */

#ifndef _Included_com_standopen_hello_MainActivity
#define _Included_com_standopen_hello_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_standopen_hello_MainActivity
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_standopen_hello_MainActivity_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_standopen_hello_MainActivity
 * Method:    getstr
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_standopen_hello_MainActivity_getstr
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_standopen_hello_MainActivity
 * Method:    intMethod
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_standopen_hello_MainActivity_intMethod
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_standopen_hello_MainActivity
 * Method:    hello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_standopen_hello_MainActivity_hello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
